spring.application.name=cardApplication
spring.datasource.url=postgresql://postgres:Forza200@localhost:5432/demodb
spring.datasource.username=postgres
spring.datasource.password=Forza200
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
